package GUIProgram;


import Controller.LecturerController;
import Entity.Subject;
import Entity.Lecturer;
import Entity.modules;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class LecturerSignUp extends javax.swing.JFrame {

    private int id;
    private String lecName;
    private int lecAge;
    private String userName;
    private String passowrd;
    private Lecturer lecturer=new Lecturer();
    private ArrayList<Subject> subjectList=new ArrayList<>();
    private LecturerController lecController=new LecturerController();
    public static LecturerSignUp lecSignUp=new LecturerSignUp();
    private HomePage homePage=new HomePage();
        
    /**
     * Creates new form MainWindow
     */
    ArrayList<Subject> sbList=new ArrayList<>();
    public LecturerSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtRePassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        checkSub1 = new javax.swing.JCheckBox();
        checkSub3 = new javax.swing.JCheckBox();
        checkSub2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("SIGN UP AS A LECTURER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(64, 60, 265, 29);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(67, 152, 90, 22);

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(67, 194, 80, 22);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel8.setText("Re Type Password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(67, 236, 153, 22);
        getContentPane().add(txtUserName);
        txtUserName.setBounds(355, 156, 308, 20);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(355, 198, 308, 20);
        getContentPane().add(txtRePassword);
        txtRePassword.setBounds(355, 240, 308, 20);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel9.setText("Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(67, 278, 130, 26);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel10.setText("Age");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(64, 322, 31, 22);
        getContentPane().add(txtName);
        txtName.setBounds(355, 284, 308, 20);
        getContentPane().add(txtAge);
        txtAge.setBounds(355, 326, 308, 20);

        checkSub1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkSub1.setText("SENG1111_Introduction_to_Programming");
        getContentPane().add(checkSub1);
        checkSub1.setBounds(64, 374, 410, 31);

        checkSub3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkSub3.setText("SENG1113_Data_Structures_and_Algorithms");
        getContentPane().add(checkSub3);
        checkSub3.setBounds(64, 442, 410, 31);

        checkSub2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkSub2.setText("SENG1112_Fndamantales_of_Engineering");
        getContentPane().add(checkSub2);
        checkSub2.setBounds(64, 408, 410, 31);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel2.setText("User Id");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(67, 117, 59, 22);
        getContentPane().add(txtUserId);
        txtUserId.setBounds(355, 121, 308, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(153, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(0, 0, 153));
        btnSignUp.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(153, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(btnSignUp)
                .addGap(71, 71, 71)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(538, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSignUp))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        try {
            // TODO add your handling code here:
            JFrame frame=new JFrame();
            id=Integer.parseInt(txtUserId.getText());
            userName=txtUserName.getText();
            lecName=txtName.getText();
            lecAge=Integer.parseInt(txtAge.getText());
            passowrd=txtPassword.getText();
            lecturer=lecController.lecSignIn(userName, passowrd);
            if(lecturer!=null){
                JOptionPane.showMessageDialog(frame, "Username or password Already Taken by another user..");
            }else{
                if(checkSub1.isSelected()){
                    Subject subject1=new Subject(1,String.valueOf(modules.SENG1111_Introduction_to_Programming));
                    subjectList.add(subject1);
                }
                if(checkSub2.isSelected()){
                    Subject subject2=new Subject(2,String.valueOf(modules.SENG1112_Fndamantales_of_Engineering));
                    subjectList.add(subject2);
                }
                if(checkSub3.isSelected()){
                    Subject subject3=new Subject(3,String.valueOf(modules.SENG1113_Data_Structures_and_Algorithms));
                    subjectList.add(subject3);
                }
                lecController.lecSignUp(id, lecName, lecAge, userName, passowrd, subjectList);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LecturerSignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LecturerSignUp.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        homePage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                lecSignUp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JCheckBox checkSub1;
    private javax.swing.JCheckBox checkSub2;
    private javax.swing.JCheckBox checkSub3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtRePassword;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
