package GUIProgram;


import Controller.StudentController;
import Entity.Student;
import Entity.Subject;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class StudentProfile extends javax.swing.JFrame {

    private HomePage homePage=new HomePage();
         
    /**
     * Creates new form StudentProfile
     */
    private Student student;
    
    public StudentProfile() {
        
    }

    public StudentProfile(Student student) throws ClassNotFoundException, SQLException {
        this.student = student;
        initComponents();
        loadStudent();
    }
    
    public void loadStudent() throws ClassNotFoundException, SQLException{
        StudentController stdController=new StudentController();
        Student tpstudent=stdController.stdSignIn(student.getUserName(), student.getPassowrd());
        lblStdID.setText(Integer.toString(tpstudent.getId()));
        lblStdName.setText(tpstudent.getStdName());
        lblStdAge.setText(Integer.toString(tpstudent.getStdAge()));
        ArrayList<Subject> subList=stdController.stdRegedSubjects(student.getUserName(), student.getPassowrd());
        DefaultTableModel dtm=(DefaultTableModel) tblStdDetails.getModel();
        dtm.setRowCount(0);
        for(Subject subject:subList){
            Object[] rowdata={subject.getId(),subject.getSubName()};
            dtm.addRow(rowdata);
        }
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStdID = new javax.swing.JLabel();
        lblStdName = new javax.swing.JLabel();
        lblStdAge = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStdDetails = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("STUDENT PROFILE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 70, 206, 29);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setText("Student ID:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(64, 130, 94, 22);

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setText("Student Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(64, 158, 123, 22);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setText("Student Age:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(64, 191, 106, 22);
        getContentPane().add(lblStdID);
        lblStdID.setBounds(327, 130, 242, 22);
        getContentPane().add(lblStdName);
        lblStdName.setBounds(327, 158, 242, 27);
        getContentPane().add(lblStdAge);
        lblStdAge.setBounds(327, 191, 242, 21);

        tblStdDetails.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        tblStdDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Course Name"
            }
        ));
        jScrollPane1.setViewportView(tblStdDetails);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(64, 213, 688, 97);

        btnBack.setBackground(new java.awt.Color(0, 0, 153));
        btnBack.setForeground(new java.awt.Color(153, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(554, 316, 55, 23);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 770, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        homePage.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStdAge;
    private javax.swing.JLabel lblStdID;
    private javax.swing.JLabel lblStdName;
    private javax.swing.JTable tblStdDetails;
    // End of variables declaration//GEN-END:variables
}
